// Code generated by goctl. DO NOT EDIT.
// Source: go_counter.proto

package server

import (
	"context"

	"go_counter/go_counter"
	"go_counter/internal/logic"
	"go_counter/internal/svc"
)

type GoCounterServer struct {
	svcCtx *svc.ServiceContext
	go_counter.UnimplementedGoCounterServer
}

func NewGoCounterServer(svcCtx *svc.ServiceContext) *GoCounterServer {
	return &GoCounterServer{
		svcCtx: svcCtx,
	}
}

func (s *GoCounterServer) Ping(ctx context.Context, in *go_counter.Request) (*go_counter.Response, error) {
	l := logic.NewPingLogic(ctx, s.svcCtx)
	return l.Ping(in)
}
