// Code generated by goctl. DO NOT EDIT.

package mysql

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	favoritesFieldNames          = builder.RawFieldNames(&Favorites{})
	favoritesRows                = strings.Join(favoritesFieldNames, ",")
	favoritesRowsExpectAutoSet   = strings.Join(stringx.Remove(favoritesFieldNames, "`favorite_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	favoritesRowsWithPlaceHolder = strings.Join(stringx.Remove(favoritesFieldNames, "`favorite_id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	favoritesModel interface {
		Insert(ctx context.Context, data *Favorites) (sql.Result, error)
		FindOne(ctx context.Context, favoriteId int64) (*Favorites, error)
		Update(ctx context.Context, data *Favorites) error
		Delete(ctx context.Context, favoriteId int64) error
	}

	defaultFavoritesModel struct {
		conn  sqlx.SqlConn
		table string
	}

	Favorites struct {
		FavoriteId int64     `db:"favorite_id"`
		UserId     int64     `db:"user_id"`
		ArticleId  int64     `db:"article_id"`
		CreatedAt  time.Time `db:"created_at"`
	}
)

func newFavoritesModel(conn sqlx.SqlConn) *defaultFavoritesModel {
	return &defaultFavoritesModel{
		conn:  conn,
		table: "`favorites`",
	}
}

func (m *defaultFavoritesModel) Delete(ctx context.Context, favoriteId int64) error {
	query := fmt.Sprintf("delete from %s where `favorite_id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, favoriteId)
	return err
}

func (m *defaultFavoritesModel) FindOne(ctx context.Context, favoriteId int64) (*Favorites, error) {
	query := fmt.Sprintf("select %s from %s where `favorite_id` = ? limit 1", favoritesRows, m.table)
	var resp Favorites
	err := m.conn.QueryRowCtx(ctx, &resp, query, favoriteId)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultFavoritesModel) Insert(ctx context.Context, data *Favorites) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?)", m.table, favoritesRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ArticleId)
	return ret, err
}

func (m *defaultFavoritesModel) Update(ctx context.Context, data *Favorites) error {
	query := fmt.Sprintf("update %s set %s where `favorite_id` = ?", m.table, favoritesRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.UserId, data.ArticleId, data.FavoriteId)
	return err
}

func (m *defaultFavoritesModel) tableName() string {
	return m.table
}
