// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.20.3
// source: go_counter.proto

package go_counter

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	GoCounter_Ping_FullMethodName = "/go_counter.Go_counter/Ping"
)

// GoCounterClient is the client API for GoCounter service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GoCounterClient interface {
	Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error)
}

type goCounterClient struct {
	cc grpc.ClientConnInterface
}

func NewGoCounterClient(cc grpc.ClientConnInterface) GoCounterClient {
	return &goCounterClient{cc}
}

func (c *goCounterClient) Ping(ctx context.Context, in *Request, opts ...grpc.CallOption) (*Response, error) {
	out := new(Response)
	err := c.cc.Invoke(ctx, GoCounter_Ping_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GoCounterServer is the server API for GoCounter service.
// All implementations must embed UnimplementedGoCounterServer
// for forward compatibility
type GoCounterServer interface {
	Ping(context.Context, *Request) (*Response, error)
	mustEmbedUnimplementedGoCounterServer()
}

// UnimplementedGoCounterServer must be embedded to have forward compatible implementations.
type UnimplementedGoCounterServer struct {
}

func (UnimplementedGoCounterServer) Ping(context.Context, *Request) (*Response, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Ping not implemented")
}
func (UnimplementedGoCounterServer) mustEmbedUnimplementedGoCounterServer() {}

// UnsafeGoCounterServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GoCounterServer will
// result in compilation errors.
type UnsafeGoCounterServer interface {
	mustEmbedUnimplementedGoCounterServer()
}

func RegisterGoCounterServer(s grpc.ServiceRegistrar, srv GoCounterServer) {
	s.RegisterService(&GoCounter_ServiceDesc, srv)
}

func _GoCounter_Ping_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Request)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GoCounterServer).Ping(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: GoCounter_Ping_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GoCounterServer).Ping(ctx, req.(*Request))
	}
	return interceptor(ctx, in, info, handler)
}

// GoCounter_ServiceDesc is the grpc.ServiceDesc for GoCounter service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GoCounter_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "go_counter.Go_counter",
	HandlerType: (*GoCounterServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Ping",
			Handler:    _GoCounter_Ping_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "go_counter.proto",
}
